image: "iras/npmtest:1.1"

variables:
  GIT_SSL_NO_VERIFY: "true"
  DISPLAY: ":23"

before_script:
  - npm -v
  - which npm

test:
  script:
    - npm install
    - npm test
    - npm run prepublish
  