image: "iras/npmtest:1.1"

variables:
  GIT_SSL_NO_VERIFY: "true"
  DISPLAY: ":23"

before_script:
  - npm -v
  - which npm
  - sh -c "/sbin/my_init" 2&>1 > /dev/null &

test:
  script:
    - npm install
    - npm test
    - npm run prepublish
  