image: "iras/npmtest:1.0"

variables:
  DISPLAY: ":23"

before_script:
  - npm -v
  - which npm
  - sh -c "/sbin/my_init" 2&>1 > /dev/null &

test:
  artifacts:
    paths:
    - coverage/
  script:
    - npm install
    - npm run tslint
    - npm run jslint
    # dirty hack because of https://github.com/angular/zone.js/issues/399
    - sed -i "s/this._uncaughtPromiseErrors = Promise\[Zone\['__symbol__'\]('uncaughtPromiseErrors')\];/this._uncaughtPromiseErrors = Promise[Zone['__symbol__'\]('uncaughtPromiseErrors')] || [];/g" node_modules/zone.js/dist/fake-async-test.js
    - npm test
    - npm run prepublish
