image: "iras/npmtest:1.0"

variables:
  DISPLAY: ":23"

artifacts:
  paths:
  - coverage/

before_script:
  - npm -v
  - which npm
  - sh -c "/sbin/my_init" 2&>1 > /dev/null &

test:
  script:
    - npm install
    - npm run tslint
    - npm run jslint
    - npm test
    - npm run prepublish
