language: node_js
node_js:
  - "stable"

matrix:
  fast_finish: true

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - npm install coveralls

script:
  - npm run tslint
  - npm test
  - npm run coveralls
